# Copyright (c) 2023, Bennett Samowich <bennett@foolean.org>
# All rights reserved
# SPDX short identifier: BSD-3-Clause
---

# We put the entire role in a block so we can create
# a role specific tag, which saves the caller from
# having to do so in their playbook.
- name: Role foolean/usb
  block:

    - name: Configure usb-storage module
      become: true
      ansible.builtin.template:
        src: 'etc/modprobe.d/usb-storage.conf.j2'
        dest: '/etc/modprobe.d/usb-storage.conf'
        owner: 'root'
        group: 'root'
        mode: '0644'
      when:
        - ansible_system == 'Linux'

    - name: Unload usb-storage module
      become: true
      ansible.builtin.modprobe:
        name: 'usb-storage'
        state: absent
      when:
        - ansible_system == 'Linux'

  when:
    # USB storage is built-in to Raspberry Pi images
    - ansible_lsb.id|lower != "raspbian"

  # Tags to be applied to this role (block)
  tags:
    - 'role_foolean_usb'
